"""Tests for AuthMiddleware internal IPC token + codec_keychain.get_internal_token.

Closes audit finding D-11 (HIGH) — replaces the trusted-header
short-circuit (`X-Internal: codec` from any localhost caller) with a
per-process HMAC token stored in macOS Keychain (or 0600 fallback
headless). PR-2D.

Reference: docs/audits/PHASE-1-SECURITY.md finding D-11.
"""
from __future__ import annotations

import os
import sys
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))


# ── Per-test isolation ──────────────────────────────────────────────────────


@pytest.fixture(autouse=True)
def _isolate_keychain(tmp_path, monkeypatch):
    """Redirect codec_keychain fallback paths + service prefix per test
    so we never touch the user's real Keychain. Mirrors test_keychain.py.
    Also invalidates the in-memory internal_token cache so each test
    starts from a clean slate."""
    import codec_keychain as kc

    monkeypatch.setattr(kc, "_FALLBACK_KEY_PATH",
                         tmp_path / "secret.key")
    monkeypatch.setattr(kc, "_FALLBACK_STORE_PATH",
                         tmp_path / "secrets.enc.json")
    test_id = f"_test_authmid_{os.getpid()}_{tmp_path.name}"
    monkeypatch.setattr(kc, "_SERVICE_PREFIX",
                         f"ai.avadigital.codec.{test_id}")
    # Wipe cached value
    kc._invalidate_internal_token_cache()
    yield kc
    # Teardown: clear any real-Keychain entries we created
    if kc.is_keychain_available():
        kc.keychain_delete(kc.KEY_INTERNAL_TOKEN)
    kc._invalidate_internal_token_cache()


@pytest.fixture
def force_fallback(monkeypatch):
    """Force is_keychain_available() to return False so we exercise the
    fallback path regardless of host OS (mirrors test_keychain.py)."""
    import codec_keychain as kc
    monkeypatch.setattr(kc, "is_keychain_available", lambda: False)
    yield kc


# ── get_internal_token bootstrap + cache tests ──────────────────────────────


def test_get_internal_token_bootstraps_on_first_call(_isolate_keychain):
    """First call must auto-generate + persist a token. Must not return None
    on a working Keychain (or fallback)."""
    kc = _isolate_keychain
    token = kc.get_internal_token()
    assert token, "get_internal_token must return non-empty on bootstrap"
    assert len(token) >= 32, f"Token must be ≥32 chars (URL-safe 32 bytes); got {len(token)}"
    # The persisted token must match what's in Keychain
    persisted = kc.keychain_get(kc.KEY_INTERNAL_TOKEN)
    assert persisted == token, "Bootstrapped token must be persisted to Keychain"


def test_get_internal_token_caches_within_ttl(_isolate_keychain):
    """Two calls within the TTL must return the same value AND avoid a
    second Keychain read (cache hit)."""
    kc = _isolate_keychain
    token1 = kc.get_internal_token()
    token2 = kc.get_internal_token()
    assert token1 == token2, "Cached token must match"
    # Cache must be populated
    assert kc._INTERNAL_TOKEN_CACHE["value"] == token1


def test_get_internal_token_cache_invalidation(_isolate_keychain):
    """After invalidate, the next call must re-read from Keychain
    (and still return the same persisted value, since we didn't delete)."""
    kc = _isolate_keychain
    token1 = kc.get_internal_token()
    kc._invalidate_internal_token_cache()
    assert kc._INTERNAL_TOKEN_CACHE["value"] is None
    token2 = kc.get_internal_token()
    assert token2 == token1, "Token persists across cache invalidation"


def test_get_internal_token_works_on_fallback(force_fallback, tmp_path, monkeypatch):
    """Headless / fallback environment must still bootstrap successfully."""
    kc = force_fallback
    monkeypatch.setattr(kc, "_FALLBACK_KEY_PATH", tmp_path / "secret.key")
    monkeypatch.setattr(kc, "_FALLBACK_STORE_PATH", tmp_path / "secrets.enc.json")
    kc._invalidate_internal_token_cache()
    token = kc.get_internal_token()
    assert token, "Bootstrap must succeed on fallback backend"
    # Round-trip
    assert kc.keychain_get(kc.KEY_INTERNAL_TOKEN) == token


def test_get_internal_token_emits_autogen_audit(_isolate_keychain, monkeypatch):
    """First-call bootstrap must emit `internal_token_autogenerated`."""
    kc = _isolate_keychain
    captured = []

    def _fake_audit(event_type, *args, **kwargs):
        captured.append({"event_type": event_type, "args": args, "kwargs": kwargs})

    monkeypatch.setattr(kc, "_kc_log_event", _fake_audit)
    kc._invalidate_internal_token_cache()
    # Ensure no pre-existing entry
    kc.keychain_delete(kc.KEY_INTERNAL_TOKEN)
    kc.get_internal_token()
    matches = [c for c in captured if c["event_type"] == "internal_token_autogenerated"]
    assert len(matches) == 1, f"Expected one autogen event; got {captured!r}"


# ── AuthMiddleware HMAC validation tests ────────────────────────────────────


@pytest.fixture
def client_localhost(_isolate_keychain):
    """TestClient impersonating a 127.0.0.1 caller — exercises the new
    HMAC-token short-circuit path. Force the dashboard module to reload
    so AuthMiddleware picks up the test-isolated Keychain backend."""
    from fastapi.testclient import TestClient
    import codec_dashboard
    return TestClient(codec_dashboard.app, client=("127.0.0.1", 12345))


@pytest.fixture
def client_non_localhost(_isolate_keychain):
    """TestClient with a non-localhost client tuple — must NEVER get the
    short-circuit even with a correct token (defense-in-depth)."""
    from fastapi.testclient import TestClient
    import codec_dashboard
    return TestClient(codec_dashboard.app, client=("192.168.1.50", 50000))


def test_authmiddleware_localhost_correct_token_passes(client_localhost, _isolate_keychain):
    """Localhost + matching HMAC token → request passes the auth gate.
    `/api/notifications/count` is protected (not in PUBLIC_ROUTES) so a
    non-auth request returns 401; with correct token, the handler runs
    and returns 200 (count payload)."""
    kc = _isolate_keychain
    token = kc.get_internal_token()
    r = client_localhost.get("/api/notifications/count",
                              headers={"x-internal-token": token})
    assert r.status_code == 200, (
        f"Localhost + correct token must pass; got {r.status_code}: {r.text[:200]}"
    )


def test_authmiddleware_localhost_wrong_token_falls_through(
    client_localhost, _isolate_keychain, monkeypatch
):
    """Localhost + WRONG token → no short-circuit. Falls through to normal
    auth, which (with no DASHBOARD_TOKEN + no biometric in test) returns 401."""
    # Force auth check to deny: ensure no DASHBOARD_TOKEN/biometric path
    monkeypatch.setattr("codec_config.get_dashboard_token", lambda: "tok-required")
    r = client_localhost.get("/api/notifications/count",
                              headers={"x-internal-token": "not-the-right-token"})
    assert r.status_code == 401, (
        f"Localhost + wrong token must fall through to 401; "
        f"got {r.status_code}: {r.text[:200]}"
    )


def test_authmiddleware_legacy_x_internal_header_is_ignored(
    client_localhost, _isolate_keychain, monkeypatch
):
    """The OLD `X-Internal: codec` header alone (without x-internal-token)
    must NO LONGER grant access. This is the D-11 closure invariant —
    spoofable by any LAN/Cloudflare caller before this PR."""
    monkeypatch.setattr("codec_config.get_dashboard_token", lambda: "tok-required")
    r = client_localhost.get("/api/notifications/count",
                              headers={"x-internal": "codec"})
    assert r.status_code == 401, (
        f"Legacy `x-internal: codec` literal must no longer grant access; "
        f"got {r.status_code}"
    )


def test_authmiddleware_non_localhost_with_token_falls_through(
    client_non_localhost, _isolate_keychain, monkeypatch
):
    """Non-localhost client + correct token → no short-circuit. Internal
    short-circuit is gated by BOTH IP and token; spoofing one without
    the other fails."""
    kc = _isolate_keychain
    token = kc.get_internal_token()
    monkeypatch.setattr("codec_config.get_dashboard_token", lambda: "tok-required")
    r = client_non_localhost.get("/api/notifications/count",
                                  headers={"x-internal-token": token})
    assert r.status_code == 401, (
        f"Non-localhost + correct token must NOT short-circuit; "
        f"got {r.status_code}"
    )


def test_authmiddleware_no_token_header_falls_through(
    client_localhost, _isolate_keychain, monkeypatch
):
    """Localhost + NO x-internal-token header → falls through to normal
    auth (most common case for browser PWA requests)."""
    monkeypatch.setattr("codec_config.get_dashboard_token", lambda: "tok-required")
    r = client_localhost.get("/api/notifications/count")
    assert r.status_code == 401


def test_authmiddleware_emits_audit_on_mismatch(
    client_localhost, _isolate_keychain, monkeypatch
):
    """A wrong token must emit `internal_token_mismatch` audit event
    so operators can grep for spoofing attempts."""
    captured = []

    def _capture(event_type, *args, **kwargs):
        captured.append({"event_type": event_type, "args": args, "kwargs": kwargs})

    monkeypatch.setattr("codec_dashboard.log_event", _capture)
    monkeypatch.setattr("codec_config.get_dashboard_token", lambda: "tok-required")
    client_localhost.get("/api/notifications/count",
                          headers={"x-internal-token": "definitely-wrong"})
    matches = [c for c in captured if c["event_type"] == "internal_token_mismatch"]
    assert len(matches) >= 1, (
        f"Expected at least one internal_token_mismatch audit; got {captured!r}"
    )
    extra = matches[0]["kwargs"].get("extra", {})
    assert "client_ip" in extra
    assert extra.get("presented_len") == len("definitely-wrong")


# ── Source-level invariants ─────────────────────────────────────────────────


def test_dashboard_source_no_longer_trusts_legacy_x_internal_literal():
    """Source check: `request.headers.get("x-internal") == "codec"` literal
    must be GONE from codec_dashboard.py. Belt-and-suspenders for the
    runtime tests above."""
    src = (REPO / "codec_dashboard.py").read_text()
    assert '"x-internal") == "codec"' not in src, (
        "Legacy x-internal: codec literal trust must be removed (D-11)"
    )
    # Ensure we DID migrate to the token name
    assert "x-internal-token" in src, (
        "codec_dashboard.py must reference the new x-internal-token header"
    )


def test_all_internal_callers_send_x_internal_token():
    """The 5 internal callers identified in PR-2D scope must send
    `x-internal-token` (not the legacy `x-internal: codec`)."""
    callers = [
        REPO / "codec_heartbeat.py",
        REPO / "codec_scheduler.py",
        REPO / "skills" / "notification_reader.py",
        REPO / "skills" / "health_check.py",
        REPO / "scripts" / "feature_audit.py",
    ]
    for caller in callers:
        src = caller.read_text()
        # New header must be present
        assert "x-internal-token" in src, (
            f"{caller.name} must send x-internal-token header (PR-2D)"
        )
        # Old literal must be gone (comments are allowed — they mention the
        # legacy header for context). We check there's no live dict entry
        # `"x-internal": "codec"` outside of comments.
        for line in src.splitlines():
            stripped = line.strip()
            if stripped.startswith("#"):
                continue
            assert '"x-internal": "codec"' not in stripped, (
                f"{caller.name}: legacy `\"x-internal\": \"codec\"` literal "
                f"must be removed (line: {stripped[:120]})"
            )


def test_authmiddleware_uses_constant_time_comparison():
    """The new validation must use `hmac.compare_digest`, not `==`.
    Constant-time comparison prevents timing side-channels on token
    guessing."""
    src = (REPO / "codec_dashboard.py").read_text()
    # Find the section that handles x-internal-token
    assert "x-internal-token" in src
    # The token comparison line must use compare_digest
    idx = src.find("x-internal-token")
    assert idx >= 0
    nearby = src[idx:idx + 800]
    assert "compare_digest" in nearby, (
        "x-internal-token validation must use hmac.compare_digest "
        "(constant-time). nearby code:\n" + nearby[:400]
    )
