"""CODEC Skill: AI News Digest — Daily AI/tech news report from public sources"""
SKILL_NAME = "AI News Digest"
SKILL_DESCRIPTION = "Fetch and summarize the latest AI and tech news from public RSS feeds and sources"
SKILL_TRIGGERS = [
    "ai news", "ai digest", "tech news", "ai report", "news digest",
    "latest ai news", "what's new in ai", "artificial intelligence news",
    "daily ai briefing", "ai headlines",
]


def run(task="", app="", ctx=""):
    """Gather AI/tech news from multiple free public sources and return a formatted digest."""
    import datetime

    today = datetime.date.today().strftime("%A, %B %d, %Y")
    sections = []

    # ── Source 1: RSS feeds (XML parsing, no API key needed) ────────────
    rss_items = _fetch_rss_feeds()

    # ── Source 2: DuckDuckGo instant answers for trending AI topics ──────
    ddg_items = _fetch_ddg_news()

    # ── Source 3: Hacker News top AI stories ─────────────────────────────
    hn_items = _fetch_hackernews()

    # ── Assemble digest ─────────────────────────────────────────────────
    all_items = rss_items + ddg_items + hn_items

    if not all_items:
        return (
            f"AI News Digest — {today}\n"
            "---\n"
            "Could not fetch news from any source. "
            "Check your network connection and try again."
        )

    # Deduplicate by title similarity
    seen_titles = set()
    unique_items = []
    for item in all_items:
        key = item["title"].lower()[:60]
        if key not in seen_titles:
            seen_titles.add(key)
            unique_items.append(item)

    # Build report
    lines = [
        f"AI & Tech News Digest — {today}",
        "=" * 50,
        "",
    ]

    # Group by source
    by_source = {}
    for item in unique_items[:20]:
        src = item.get("source", "Other")
        by_source.setdefault(src, []).append(item)

    for source, items in by_source.items():
        lines.append(f"--- {source} ---")
        for item in items:
            lines.append(f"  * {item['title']}")
            if item.get("snippet"):
                lines.append(f"    {item['snippet'][:200]}")
            if item.get("link"):
                lines.append(f"    {item['link']}")
            lines.append("")
        lines.append("")

    lines.append(f"Total stories: {len(unique_items)}")
    lines.append("---")
    lines.append("Generated by CODEC AI News Digest skill")

    return "\n".join(lines)


# ── RSS feed parser ─────────────────────────────────────────────────────────

def _fetch_rss_feeds():
    """Parse RSS/Atom feeds from major AI/tech news sources."""
    import xml.etree.ElementTree as ET

    feeds = [
        ("MIT Technology Review - AI", "https://www.technologyreview.com/feed/"),
        ("TechCrunch - AI", "https://techcrunch.com/category/artificial-intelligence/feed/"),
        ("The Verge - AI", "https://www.theverge.com/rss/ai-artificial-intelligence/index.xml"),
        ("Ars Technica - AI", "https://feeds.arstechnica.com/arstechnica/technology-lab"),
        ("VentureBeat - AI", "https://venturebeat.com/category/ai/feed/"),
    ]

    items = []
    for source_name, url in feeds:
        try:
            import requests
            r = requests.get(url, timeout=10, headers={
                "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) CODEC-Agent/1.0"
            })
            if r.status_code != 200:
                continue

            root = ET.fromstring(r.content)

            # Handle both RSS 2.0 and Atom feeds
            ns = {"atom": "http://www.w3.org/2005/Atom"}

            # RSS 2.0: <channel><item>
            for item_el in root.findall(".//item")[:5]:
                title = _text(item_el, "title")
                link = _text(item_el, "link")
                desc = _text(item_el, "description")
                if title:
                    items.append({
                        "title": _clean(title),
                        "link": link or "",
                        "snippet": _clean(desc)[:200] if desc else "",
                        "source": source_name,
                    })

            # Atom: <entry>
            for entry in root.findall(".//atom:entry", ns)[:5]:
                title = _text(entry, "atom:title", ns)
                link_el = entry.find("atom:link", ns)
                link = link_el.get("href", "") if link_el is not None else ""
                summary = _text(entry, "atom:summary", ns) or _text(entry, "atom:content", ns)
                if title:
                    items.append({
                        "title": _clean(title),
                        "link": link,
                        "snippet": _clean(summary)[:200] if summary else "",
                        "source": source_name,
                    })

        except Exception:
            continue

    return items


def _text(el, tag, ns=None):
    """Safely get text from an XML element."""
    child = el.find(tag, ns) if ns else el.find(tag)
    if child is not None and child.text:
        return child.text.strip()
    return ""


def _clean(text):
    """Strip HTML tags and excess whitespace from text."""
    import re
    if not text:
        return ""
    text = re.sub(r"<[^>]+>", "", text)
    text = re.sub(r"\s+", " ", text)
    return text.strip()


# ── DuckDuckGo news ────────────────────────────────────────────────────────

def _fetch_ddg_news():
    """Fetch AI-related news via DuckDuckGo instant answers."""
    items = []
    queries = ["artificial intelligence news today", "AI breakthrough 2026"]

    for query in queries:
        try:
            import requests
            r = requests.get(
                "https://api.duckduckgo.com/",
                params={"q": query, "format": "json", "no_html": 1, "skip_disambig": 1},
                timeout=10,
            )
            if r.status_code == 200:
                data = r.json()
                if data.get("AbstractText"):
                    items.append({
                        "title": data.get("Heading", query),
                        "link": data.get("AbstractURL", ""),
                        "snippet": data["AbstractText"][:200],
                        "source": "DuckDuckGo",
                    })
                for topic in data.get("RelatedTopics", [])[:3]:
                    if isinstance(topic, dict) and topic.get("Text"):
                        items.append({
                            "title": topic["Text"][:80],
                            "link": topic.get("FirstURL", ""),
                            "snippet": topic["Text"][:200],
                            "source": "DuckDuckGo",
                        })
        except Exception:
            continue

    return items


# ── Hacker News ─────────────────────────────────────────────────────────────

def _fetch_hackernews():
    """Fetch top Hacker News stories filtered for AI/ML relevance."""
    items = []
    ai_keywords = {
        "ai", "artificial intelligence", "machine learning", "llm", "gpt",
        "openai", "anthropic", "claude", "gemini", "neural", "deep learning",
        "transformer", "diffusion", "chatbot", "copilot", "model", "training",
        "inference", "agents", "autonomous", "robotics", "computer vision",
    }

    try:
        import requests
        r = requests.get(
            "https://hacker-news.firebaseio.com/v0/topstories.json",
            timeout=10,
        )
        if r.status_code != 200:
            return items

        story_ids = r.json()[:60]  # Check top 60 stories

        for sid in story_ids:
            if len(items) >= 8:
                break
            try:
                sr = requests.get(
                    f"https://hacker-news.firebaseio.com/v0/item/{sid}.json",
                    timeout=5,
                )
                if sr.status_code == 200:
                    story = sr.json()
                    title = story.get("title", "")
                    title_lower = title.lower()
                    if any(kw in title_lower for kw in ai_keywords):
                        items.append({
                            "title": title,
                            "link": story.get("url", f"https://news.ycombinator.com/item?id={sid}"),
                            "snippet": f"Score: {story.get('score', 0)} | Comments: {story.get('descendants', 0)}",
                            "source": "Hacker News",
                        })
            except Exception:
                continue

    except Exception:
        pass

    return items


# ── Allow direct execution for testing ──────────────────────────────────────
if __name__ == "__main__":
    print(run())
