#!/usr/bin/env python3
"""Generate / verify the trusted-skill manifest used by SkillRegistry.

Background (closes audit finding D-1, see docs/audits/PHASE-1-SECURITY.md):
    `SkillRegistry.load` runs an AST safety check against every skill source
    before `exec_module`. The check correctly flags any source containing
    `import subprocess`, `os.system`, `eval`, etc. — but CODEC's built-in
    skills (calculator, system, file_write, pilot, ...) legitimately use
    those patterns. Solution: a committed manifest of SHA-256 hashes of
    every approved built-in skill source. On `load()`, the registry computes
    the file's hash and bypasses the AST check IFF the hash is in the
    manifest. Any file an attacker drops in `~/.codec/skills/` (or alters
    in `<repo>/skills/`) won't match a manifest hash → AST check runs →
    refused fail-closed.

Workflow:
    # After legitimately adding / editing a built-in skill in <repo>/skills/:
    python3 tools/generate_skill_manifest.py --write
    git add skills/.manifest.json
    git commit -m "chore(skills): regenerate trusted-skill manifest"

    # CI verifies no drift:
    python3 tools/generate_skill_manifest.py --check
    # exit 0 if manifest is current; exit 1 (with diff) if drift.

Files NOT included in the manifest:
    - Files starting with `_` (private / template).
    - `codec.py` (per existing tests/test_skill_contracts.py NON_SKILL_FILES).
      It's a 460-LOC stale fork of the main entry point per audit finding A-2
      and is NOT a valid skill — including it would create a permanent
      manifest entry for dead code.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SKILLS_DIR = REPO / "skills"
MANIFEST_PATH = SKILLS_DIR / ".manifest.json"

# Match tests/test_skill_contracts.py NON_SKILL_FILES — keeps the manifest's
# definition of "a built-in skill" aligned with the contract test.
EXCLUDE_FILENAMES = {"codec.py"}

MANIFEST_SCHEMA_VERSION = 1


def _hash_file(path: Path) -> str:
    """Return the SHA-256 of the file's bytes (raw, not text — robust to
    line-ending or encoding ambiguity)."""
    h = hashlib.sha256()
    h.update(path.read_bytes())
    return h.hexdigest()


def compute_current_manifest() -> dict:
    """Walk `<repo>/skills/`, hash every eligible `.py` file, return the
    manifest dict that would be written to disk."""
    skills: dict[str, str] = {}
    for f in sorted(SKILLS_DIR.glob("*.py")):
        if f.name.startswith("_"):
            continue
        if f.name in EXCLUDE_FILENAMES:
            continue
        skills[f.name] = _hash_file(f)
    return {
        "schema": MANIFEST_SCHEMA_VERSION,
        "_comment": (
            "Trusted-skill manifest. Each entry is sha256(file-bytes) of an "
            "approved built-in skill source. Generated by "
            "tools/generate_skill_manifest.py — do not edit by hand. "
            "Regenerate after any legitimate change to a built-in skill and "
            "commit the diff. See docs/audits/PHASE-1-SECURITY.md D-1."
        ),
        "skills": skills,
    }


def load_existing_manifest() -> dict | None:
    if not MANIFEST_PATH.exists():
        return None
    try:
        return json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as e:
        print(f"warning: manifest at {MANIFEST_PATH} unreadable: {e}", file=sys.stderr)
        return None


def write_manifest(manifest: dict) -> None:
    MANIFEST_PATH.write_text(
        json.dumps(manifest, indent=2, sort_keys=False) + "\n",
        encoding="utf-8",
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0] if __doc__ else "")
    group = parser.add_mutually_exclusive_group()
    group.add_argument(
        "--write", action="store_true",
        help="Write the current manifest to skills/.manifest.json (default).",
    )
    group.add_argument(
        "--check", action="store_true",
        help="Compare the current manifest against the committed file; "
             "exit 1 if drift exists (with a diff to stderr).",
    )
    args = parser.parse_args(argv)

    current = compute_current_manifest()

    if args.check:
        existing = load_existing_manifest()
        if existing is None:
            print(
                f"error: manifest {MANIFEST_PATH} missing; run with --write.",
                file=sys.stderr,
            )
            return 1
        if existing.get("skills") != current["skills"]:
            print(
                f"error: trusted-skill manifest at {MANIFEST_PATH} is out of date.\n"
                "       Run: python3 tools/generate_skill_manifest.py --write\n"
                "       Then commit the diff.",
                file=sys.stderr,
            )
            # Surface the specific drift for the human / CI log.
            old = existing.get("skills", {})
            new = current["skills"]
            added = sorted(set(new) - set(old))
            removed = sorted(set(old) - set(new))
            changed = sorted(k for k in set(old) & set(new) if old[k] != new[k])
            if added:
                print(f"  added:   {', '.join(added)}", file=sys.stderr)
            if removed:
                print(f"  removed: {', '.join(removed)}", file=sys.stderr)
            if changed:
                print(f"  changed: {', '.join(changed)}", file=sys.stderr)
            return 1
        print(f"ok: {MANIFEST_PATH} matches {len(current['skills'])} built-in skills.")
        return 0

    # Default + --write: regenerate.
    write_manifest(current)
    print(f"wrote: {MANIFEST_PATH} ({len(current['skills'])} skills)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
